#!/bin/bash

#SBATCH --job-name=test_CINDES
#SBATCH --mem=4GB
#SBATCH --time=4-00:00:00
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --output=logs/cindes_%j.out
#SBATCH --error=logs/cindes_%j.err

# Make sure the logs directory exists
mkdir -p logs

# Load the right module
module load matplotlib/3.9.2-gfbf-2024a

# Set PYTHONPATH so that Python finds your package
export PYTHONPATH=$PYTHONPATH:/data/brussel/101/vsc10196/testing_program/cindes/

# Set PATH so that module finds qsta script
export PATH=$VSC_HOME/bin:$PATH

# Go to the right work directory (optional)
#cd /path/to/folder

# Execute the program
python -m CINDES -i INPUT > cindes_output.log

