#!/bin/env python
'''An convenience script for plotting and calculating properties from the cyclesinfo file generated by the 
INDES / CINDES program. 

There is a small set of analyzing scripts:
 - cyreader.py
 - fitter.py: analyzes table
 - unpickler.py
deprecated:
 - logalyzer
 - molyzer
written by Jos L. Teunissen
'''
import argparse
parser = argparse.ArgumentParser(description="reads cycles data stored in cyclesinfo")
parser.add_argument("-p","--pplot",action="store_true",help="make a site vs property plot of the data")
parser.add_argument("-s","--splot",action="store_true",help="make a plot of sitevalues of cycle0 vs cycle-1")
parser.add_argument("-c","--cplot",action="store_true",help="make a plot of cyclevalues of cycle0 vs cycle-1")
parser.add_argument("-t","--tplot",action="store_true",help="make a tablebin-like plot of cyclevalues of property vs. structure (chronologically)")
parser.add_argument("-T","--table",action="store_true",help="make a table dictionary with only single occupancy of that site for regression")
parser.add_argument("-x","--regxy",action="store_true",help="make a plot of two propeties against each other and test linear correlation")
parser.add_argument("-m","--minmax",nargs=2,help="use global cycles value1 until value2 \nNB: startcount = 0!")
parser.add_argument("-l","--label",type=str,help="property type label")
parser.add_argument('file', nargs='?', default='cyclesinfo',help='filename default is "cyclesinfo"')
args=parser.parse_args()
import matplotlib.pyplot as plt
import numpy as np
import pprint
pp = pprint.PrettyPrinter(indent=4, width=150)
from re import findall
from copy import deepcopy
import sys
import os

class Unbuffered(object):
    def __init__(self,stream):
        self.stream = stream
    def write(self,data):
        self.stream.write(data)
        self.stream.flush()
    def __getattr__(self,attr):
        return getattr(self.stream, attr)
sys.stdout = Unbuffered(sys.stdout)

def indtocon(index):
    #return [list(item) for item in index.split('_')]
    #return  [ findall('[A-Z][^A-Z]*',item) for item in index.split('_') ]
    return  tuple( findall('[A-Z0-9][^A-Z1-9]*',item) for item in index.split('_') )

if False:
    from cclib.parser import ccopen
    import logging
    import fnmatch
    allfiles = os.listdir('databc')
    path = os.getcwd()

def get_homo(conf):
    for file in allfiles:
        if fnmatch.fnmatch(file,  '*' + conf + '.log'):  
            filetje = file
            filetje = path + '/databc/' + filetje
    f = ccopen(filetje)
    f.logger.setLevel(logging.ERROR)
    datatje = f.parse()
    HOMO = datatje.myhomos[1]
    Ehomo=datatje.mymos[1]['alpha'][0][HOMO]
    #Ehomo= datatje.moenergies[0][datatje.homos[0]]
    #print 'conf:', conf, 'Ehomo:', Ehomo, 'Ehomo/27.211:', Ehomo/27.211
    Elumo= datatje.moenergies[0][datatje.homos[0]+1]
    return Ehomo

def make_table(confs,data):
    from collections import OrderedDict
    table = OrderedDict()
    for index, value in zip(confs,data):
        if not index in table:
            table[index] = value
    return table


def main():
    with open(args.file,'r') as fid:
        data = [ item.split() for item in fid.read().splitlines() ]
    datar=[]
    confs=[]
    values=[]
    prop=1
    n=len(data)
    print 'len(data)', n
    rows, columns = os.popen('stty size', 'r').read().split()
    print 'console width=', columns
    for item in data:
        #print "item:",item
        conf = item[0].replace("'","")
        if 1==1:
            if len(item)==5:
                item = [ item[0].replace("'",""), float(item[1]), int(item[2]), int(item[3]), int(item[4]) ]
                value = (float(item[1]),int(item[2]),int(item[3]),int(item[4]))
            elif len(item)==6:
                item = [ item[0].replace("'",""), float(item[1]),float(item[2]), int(item[3]), int(item[4]), int(item[5]) ]
                value = (float(item[1]),float(item[2]),int(item[3]),int(item[4]),int(item[5]))
            elif len(item)==7:
                item = [ item[0].replace("'",""), float(item[1]),float(item[2]),float(item[3]), int(item[4]), int(item[5]), int(item[6]) ]
                value = (float(item[1]),float(item[2]),float(item[3]),int(item[4]),int(item[5]),int(item[6]))
            elif len(item)>7:
                #print "I'm here"
                indices = map(int,item[-3:])
                rest = map(float,item[1:-3])
                value = rest + indices
                item = [ item[0].replace("'","") ] + value
        else:
            if len(item)==5:
                sys.stdout.write('#')
                item = [ item[0].replace("'",""), float(item[1]), int(item[2]), int(item[3]), int(item[4]) ]
                homo = get_homo(conf)
                value = (float(item[1])*27.2113838,-homo,int(item[2]),int(item[3]),int(item[4]))
            elif len(item)==7:
                sys.stdout.write('#')
                item = [ item[0].replace("'",""), float(item[1]), float(item[2]), float(item[3]),int(item[4]), int(item[5]), int(item[6]) ]
                homo = get_homo(conf)
                value = (float(item[1])*27.2113838,-homo,int(item[2]),int(item[3]),int(item[4]))
                
        item[0]=item[0].split('_')
        if item[1]:
        #if item[1]<1000:
            datar.append(item)
            confs.append(conf)
            values.append(value)
    for br in datar:
        # each site wordt geformat tot 8 width. die worden samen gejoind en weer geformat samen met de rest
        print '{0} {1:8.5}  {2:3}  {3:3}  {4:3}'.format(' '.join(['{:8}'.format(item) for item in br[0]]),br[prop],br[-3],br[-2],br[-1])
    #print confs
    #print "values:",values
    print "len(values):", len(values)
    maxmacrocycles= values[-1][-3]
    nsites = values[-1][-1]
    print "maxcycles:",maxmacrocycles #starts counting at 1
    print "nsites:", nsites+1 #starts counting at 0
    sites=[] #list of all the changing sites only
    for conf,value in zip(confs,values):
        siteindex=value[-2]
        site = conf.split('_')[siteindex]
        sites.append(site)

    # There are two main data containers:
    #    - totalruns    #on chronological order
    #    - totalsites   #in numbered site order
    ##################### make totalruns list ################
    cyclesdata=[]
    runs=[]
    macrocycle=0
    i=0
    maxnsites=0
    totalruns=[]
    #run over all macrocycles:
    #for j in range(1,maxmacrocycles+1):
    for j in range(maxmacrocycles+1):
        runsA=[]
        #run over all sites in a cycles
        for k in range(nsites+1):
            runA=[]
            # run over all substituents
            while True:
                #print "values[i]", values[i]
                #print "i=", i, "j=",j,"k=", k
                #as long as the site index and cycle index do not change:
                if values[i][-1]==k and values[i][-3]==j:
                    runA.append([sites[i],values[i]])
                    #print "Jos"
                    #print "runA:", runA
                else:
                    #print "geen Jos"
                    #i+=1
                    break
                i+=1
                if i>=len(values): break
                #print "runA:", runA
            #to get the list alphabetically ordered:
            sortA = sorted(runA)
            if len(runA)>maxnsites: maxnsites=len(runA) # to get the right ticks in the plots
            #then there is mostly one problem. The CO group is above the N group only for the
            #secondary positions. So we want to pick the CO group and place it at the end of the list
            #1. get a list of the substituents 
            subsA = [ item[0] for item in sortA]
            # check is 'CO' is in
            group = 'CO'
            if group in subsA:
                #get index of the group
                igroup = subsA.index(group)
                #take it from the list is pop
                #and insert it at the last position of the list
                sortA.insert(len(subsA)-1, sortA.pop(igroup))
            if not sortA==[]: runsA.append(sortA)
        if not runsA==[]: totalruns.append(runsA)
    #print "runsA"
    #pp.pprint(runsA)

    # NOW FORMED ARE: TOTALRUNS
    #now restrict it to only the cycles we need.
    if args.minmax:
        m1 = int( args.minmax[0] )
        m2 = int( args.minmax[1] ) + 1
        totalruns = totalruns[:][m1:m2]

    print "totalruns:"
    pp.pprint(totalruns)
    print "best substituent per site per run:"
    for run in totalruns:
        for site in run:
            print min(site, key= lambda x: x[1][0])
    print '='*20


    #################  MAKE totalsites ####################
    # these were at chronological order. also make a totalruns with site order 0,1,2 etc.
    totalsites=deepcopy(totalruns)
    for runs in totalsites:
       runs.sort(key= lambda x: x[0][1][-2]) #runs sorts by number of site. the [0] is just arbitrary here because each elements has same values
    print "totalsites:"
    pp.pprint(totalsites)
    print '='*20

    ################## MAKE table with only single attendance:
    if args.table:
        table = make_table(confs,values)
        pp.pprint(table.items()[0:4])


    # plot of property vs dopant/substituent
    if args.pplot:
        import seaborn as sb
        #for runs in totalruns:
        tags=['ro','bs','g^','c*','mp','y|','k+','rd','bv','gh']
        tags=['-ro','-bs','-g^','-c*','-mp','-y|','-k+','-rd','-bv','-gh']
        tags=['-o','-s','-^','-*','-p','-<','->','-d','-v','-h']
        #colors = sb.color_palette("viridis", n_colors=12)
        colors = sb.hls_palette(10)
        #for multiple sites:
        #for i in range(len(totalruns)-1): #-1 because last runs always same as one but last
        #otherwise:
        if True:
            i = len(totalsites)-1
            #do for each site:
            for j in range(len(totalsites[i])):
            #for run in totalruns[i]:
                run=totalsites[i][j]
                x = np.array(range(len(run)))
                if len(run) == maxnsites:
                    my_xticks = [ item[0] for item in run ] 
                    plt.xticks(x,my_xticks)
                    print "my_xticks", my_xticks
                y = [ item[1][0] for item in run ]
                #print "y=", y
                #itje = 2*(len(totalruns)-1)*i+j #index that cares for different dots/squares per site per cycle
                itje = j
                plt.plot(x,y,tags[itje],label='cycle:'+ str(i+1) + ' site:' + str(j+1), color=colors[itje])
        legend=plt.legend(loc='best', fancybox=True, framealpha=0.5)
        #plt.ylabel('ionization potential (a.u.)')
        #plt.ylabel('ionization potential (eV)')
        plt.ylabel(args.label)
        plt.xlabel('substituent')
        plt.title('property vs substituent')
        plt.show()

    if args.tplot: #get a tablebin like plot
        import seaborn as sb
        colors = sb.hls_palette(10,l=.4) #l=lightness the smaller the darker. 
        print "tablebin-like plot"
        binlist = []
        start=0
        for i in range(len(totalruns)):
             binlistje = []
             for j in range(len(totalruns[i])):
                 l = [ item[1][0] for item in totalruns[i][j] ] 
                 #print "i,j:", i,j, "l:", l
                 a = list(enumerate(l,start))
                 start += len(l)
                 binlistje.append(a)
             binlist.append(binlistje)
        pp.pprint(binlist)
        #tags=['ro','bs','g^','c*','mp','yv','k+','r|','bd','gh']
        tags=['o','s','^','*','p','v','<','>','d','h']
        for i in range(len(binlist)):
            for j in range(len(binlist[i])):
                a = np.array(binlist[i][j]).T
                site = totalruns[i][j][0][1][-2]
                a, = plt.plot(a[0],a[1],tags[site]+'-',color=colors[site],
                                                       markersize=5)
                plt.setp(a, linewidth=1)
                ax=plt.gca()
                ax.xaxis.grid(False) 
                if i==0: 
                    a.set_label('site:'+str(site+1))
            plt.axvline(x= binlist[i][-1][-1][0]+0.5, linewidth=2, color = 'k')
 
        #to reorder the legend 
        ax = plt.gca()
        handles, labels = ax.get_legend_handles_labels()
        # sort both labels and handles by labels
        labels, handles = zip(*sorted(zip(labels, handles), key=lambda t: int(t[0][5:])))
        ax.legend(handles, labels)        
        leg = plt.gca().get_legend()
        ltext  = leg.get_texts()
        plt.setp(ltext, fontsize=14) 
        #plt.ylabel('property value')
        plt.ylabel(args.label)
        plt.title('chronological order of property vs molecular structures')
        plt.show()

    #plot property values of first cycle versus property values of last cycle
    if False:
        xs = [ item[1][0] for listje in totalsites[0] for item in listje ] #values of first run
        ys = [ item[1][0] for listje in totalsites[-1] for item in listje ] #values of last run
        labels = [ item[0] for listje in totalsites[0] for item in listje ] 
        print "labels= " , labels
        plt.plot(xs,ys,'ro')
        for label, x, y in zip(labels,xs,ys):
            plt.annotate(
                label, xy = (x, y), xytext = (20, -20),
                textcoords = 'offset points', ha = 'left', va = 'bottom',
                bbox = dict(boxstyle = 'round,pad=0.5', fc = 'yellow', alpha = 0.5),
                arrowprops = dict(arrowstyle = '->', connectionstyle = 'arc3,rad=0'))
        xm = min([ min(xs),min(ys) ] )
        ym = max([ max(xs),max(ys) ] )
        print "xm:",xm, "ym:",ym
        xl = np.linspace(xm,ym,100)
        yl = xl
        plt.plot(xl,yl, 'k-')
        #plt.xlabel('stabvalues first cycle (kJ/mol)')
        #plt.ylabel('stabvalues last cycle (kJ/mol)')
        plt.xlabel(args.label + ' first cycle')
        plt.ylabel(args.label + ' last cycle')
        plt.title('last cycle vs. first cycle')
        plt.show()

    if args.cplot: #plot something to compare the different site
        from matplotlib.legend_handler import HandlerLine2D
        tags=['ro','bs','g^','c*','mp','yv','k+','r|','bd','gh']
        X = []
        Y = []
        for site0,site1,tag,i in zip(totalsites[0],totalsites[-1],tags[:len(totalsites[0])],range(len(totalsites[0]))):
            xs = [ item[1][0] for item in site0 ]
            ys = [ item[1][0] for item in site1 ]
            labels = [ item[0] for item in site0 ]
            a, = plt.plot(xs,ys,tag)
            a.set_label('site:'+str(i))
            for label, x, y in zip(labels,xs,ys):
                if False: #for boxes set to True
                    plt.annotate(
                        label, xy = (x, y), xytext = (20, -20),
                        textcoords = 'offset points', ha = 'left', va = 'bottom',
                        bbox = dict(boxstyle = 'round,pad=0.5', fc = 'yellow', alpha = 0.5),
                        arrowprops = dict(arrowstyle = '->', connectionstyle = 'arc3,rad=0'))
            X.append(min([ min(xs),min(ys) ] ))
            Y.append(max([ max(xs),max(ys) ] ))
            #plt.legend(handler_map={a:HandlerLine2D(numpoints=4)})
        print "xm:",min(X), "ym:",max(Y)
        plt.legend(loc='best', shadow= True)
        #xl = np.linspace(min(X)*0.9,max(Y)*1.1,100)
        xl = np.linspace(min(X),max(Y),100)
        yl = xl
        plt.plot(xl[:],yl[:], 'k-')
        #plt.xlabel('stabvalues first cycle (kJ/mol)')
        #plt.xlabel('IP first cycle (a.u.)')
        #plt.xlabel('electron affinities first cycle (hartree)')
        #plt.xlabel('bandgap first cycle (eV)')

        #plt.ylabel('stabvalues last cycle (kJ/mol)')
        #plt.ylabel('IP last cycle (a.u.)')
        #plt.ylabel('bandgap last cycle (eV)')
        #plt.ylabel('electron affinities last cycle (hartree)')
        plt.xlabel(args.label + ' first cycle')
        plt.ylabel(args.label + ' last cycle')
        plt.title('last cycle vs. first cycle')
        plt.show()

    if args.splot: 
        '''try subplot splot'''
        from matplotlib.legend_handler import HandlerLine2D
        tags=['ro','bs','g^','c*','mp','yv','k+','r|','bd','gh']
        #subplots = tuple( (3,2,i) for i in range(1,7))
        X = []
        Y = []
        #f, axs = plt.subplots(3,2,sharex=True,sharey=True)
        nx,ny = set_nxy(len(totalsites[0]))
        print nx, ny
        f, axs = plt.subplots(ny,nx)
        axs2d = [ item for sublist in axs for item in sublist ]
        print "axs2d:",axs2d
        for site0,site1,tag,i in zip(totalsites[0],totalsites[-1],tags[:len(totalsites[0])],range(len(totalsites[0]))):
            xs = [ item[1][0] for item in site0 ]
            ys = [ item[1][0] for item in site1 ]
            labels = [ item[0] for item in site0 ]
            #plt.subplot(*subplots[i])
            #a, = plt.plot(xs,ys,tag)
            a=axs2d[i]
            print a
            a.plot(xs,ys,tag,label='site:' + str(i+1))
            #f.set_label('site:'+str(i))
            for label, x, y in zip(labels,xs,ys):
                if False: #for boxes set to True
                    plt.annotate(
                        label, xy = (x, y), xytext = (20, -20),
                        textcoords = 'offset points', ha = 'left', va = 'bottom',
                        bbox = dict(boxstyle = 'round,pad=0.5', fc = 'yellow', alpha = 0.5),
                        arrowprops = dict(arrowstyle = '->', connectionstyle = 'arc3,rad=0'))
            X.append(min([ min(xs),min(ys) ] ))
            Y.append(max([ max(xs),max(ys) ] ))
            #plt.legend(handler_map={a:HandlerLine2D(numpoints=4)})
            print "xm:",min(X), "ym:",max(Y)
            #xl = np.linspace(min(X)*0.9,max(Y)*1.1,100)
            xl = np.linspace(min(X),max(Y),100)
            yl = xl
            a.plot(xl[:],yl[:], 'k-')
            #for the legend:
            handles, labels = a.get_legend_handles_labels()
            a.legend(handles, labels, loc='best', fancybox=True, framealpha=0.5, numpoints=1)
        # how many unneeded plots are there?
        unneed = nx*ny - len(totalsites[0])
        for i in range(1,unneed+1):
            print "i:", i
            axs2d[-i].set_frame_on(False)
            axs2d[-i].axes.get_yaxis().set_visible(False)
            axs2d[-i].axes.get_xaxis().set_visible(False)
            axs2d[-1].get_xaxis().tick_bottom()

        #plt.xlabel('stabvalues first cycle (kJ/mol)')
        #plt.xlabel('IP first cycle (a.u.)')
        #plt.xlabel('electron affinities first cycle (hartree)')
        suplabel('x',args.label + ' first cycle',labelpad=5)
        suplabel('y',args.label + ' last cycle',labelpad=4)
        #suplabel('x','bandgap first cycle (eV)',labelpad=5)
        #suplabel('y','bandgap last cycle (eV)',labelpad=4)
        #plt.xlabel('bandgap first cycle (eV)')
        #plt.ylabel('bandgap last cycle (eV)')
        #plt.ylabel('electron affinities last cycle (hartree)')
        f.suptitle('last cycle vs. first cycle')
        plt.show()
        
    #plt.axis([0,150,0,10])
    if args.regxy: # plots two properties vs each other. and fits a straight line through it
        from scipy import stats
        propx = [ item[0] for item in values ] 
        propy = [ item[1] for item in values ]
        plt.plot(propx,propy,'.r')
        slope, intersept, r_value, p_value, std_err = stats.linregress(propx,propy)
        print "slope:", slope
        print "intersept:", intersept
        print "p_value:", p_value
        print "std_err:", std_err
        print "R=",r_value**2
        x = sorted(propx)
        y = [ slope*xje+intersept for xje in x ]
        plt.plot(x, y, '-')
        plt.xlabel('property1 IP(eV)')
        plt.ylabel('property2 -Ehomoe(eV)')
        plt.title('two properties regression')
        plt.show()

def set_nxy(n):
    xys = { '1':(1,1),
            '2':(2,1), '3':(2,2), '4':(2,2), '5':(3,2), '6':(3,2), '7':(4,2), '8':(4,2), '9':(3,3), '10':(4,3) 
          }
    return xys[str(n)]


def suplabel(axis,label,label_prop=None,
             labelpad=5,
             ha='center',va='center'):
    ''' Add super ylabel or xlabel to the figure
    Similar to matplotlib.suptitle
    axis       - string: "x" or "y"
    label      - string
    label_prop - keyword dictionary for Text
    labelpad   - padding from the axis (default: 5)
    ha         - horizontal alignment (default: "center")
    va         - vertical alignment (default: "center")
    '''
    import matplotlib.pylab as pylab
    fig = pylab.gcf() #get currenct figure
    xmin = []
    ymin = []
    for ax in fig.axes:
        xmin.append(ax.get_position().xmin)
        ymin.append(ax.get_position().ymin)
    xmin,ymin = min(xmin),min(ymin)
    dpi = fig.dpi
    if axis.lower() == "y":
        rotation=90.
        x = xmin-float(labelpad)/dpi
        y = 0.5
    elif axis.lower() == 'x':
        rotation = 0.
        x = 0.5
        y = ymin - float(labelpad)/dpi
    else:
        raise Exception("Unexpected axis: x or y")
    if label_prop is None: 
        label_prop = dict()
    pylab.text(x,y,label,rotation=rotation,
               transform=fig.transFigure,
               ha=ha,va=va,
               **label_prop)






if __name__ == "__main__":
    main()
