#!/bin/bash

#SBATCH --job-name=test_CINDES
#SBATCH --mem=4GB
#SBATCH --time=4-00:00:00
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --output=logs/cindes_%j.out
#SBATCH --error=logs/cindes_%j.err

# Zorg dat de logs-map bestaat
mkdir -p logs

# Laad de juiste module
module load matplotlib/3.9.2-gfbf-2024a

# Zet PYTHONPATH zodat Python je package vindt
export PYTHONPATH=$PYTHONPATH:/user/brussel/101/vsc10196/testing_program/CINDES/

# Zet PATH zodat module qsta vindt
export PATH=$VSC_HOME/bin:$PATH

# Ga naar de juiste werkdirectory (optioneel)
#cd /path/to/folder

# Voer het programma uit
python -m CINDES -i INPUT_FINAL > cindes_output.log

