#!/bin/env python
'''An convenience script for plotting and calculating properties from the cyclesinfo file generated by the 
INDES / CINDES program. 

There is a small set of analyzing scripts:
 - cyreader.py
 - fitter.py: analyzes table
 - unpickler.py
deprecated:
 - logalyzer
 - molyzer
written by Jos L. Teunissen
'''
import argparse
parser = argparse.ArgumentParser(description="reads cycles data stored in cyclesinfo")
parser.add_argument("-p","--pplot",action="store_true",help="make a site vs property plot of the data")
parser.add_argument("-s","--splot",action="store_true",help="make a plot of sitevalues of cycle0 vs cycle-1")
parser.add_argument("-c","--cplot",action="store_true",help="make a plot of cyclevalues of cycle0 vs cycle-1")
parser.add_argument("-H","--homo",action="store_true",help="get the HOMO levels from the databc directory")
parser.add_argument("-t","--tplot",action="store_true",help="make a tablebin-like plot of cyclevalues of property vs. structure (chronologically)")
parser.add_argument("-T","--table",action="store_true",help="make a table dictionary with only single occupancy of that site for regression")
parser.add_argument("-x","--regxy",action="store_true",help="make a plot of two propeties against each other and test linear correlation")
parser.add_argument("-m","--minmax",nargs=2,help="use global cycles value1 until value2 \nNB: startcount = 0!")
parser.add_argument("-l","--label",type=str,help="property type label", default='')
parser.add_argument("-d","--datacolumn",type=int,default=1,help="which data column to choose")
parser.add_argument('file', nargs='?', default='cyclesinfo',help='filename default is "cyclesinfo"')
args=parser.parse_args()
import matplotlib.pyplot as plt
import matplotlib
import numpy as np
import pprint
pp = pprint.PrettyPrinter(indent=4, width=150)
from re import findall
import re
from copy import deepcopy
import sys
import os
rows, columns = os.popen('stty size', 'r').read().split()
print 'console width=', columns

class Unbuffered(object):
    def __init__(self,stream):
        self.stream = stream
    def write(self,data):
        self.stream.write(data)
        self.stream.flush()
    def __getattr__(self,attr):
        return getattr(self.stream, attr)
sys.stdout = Unbuffered(sys.stdout)

matplotlib.use('GTK')
#matplotlib.rcParams['text.usetex']=True
#matplotlib.rcParams['text.latex.unicode']=True
matplotlib.rcParams['mathtext.default']='regular'
funcs_r = {'CCFFF': '$C-CF_3$',
         'CCHHH': '$C-CH_3$',
         'CCN': '$C-C\\equiv N$',
         'CCl': '$C-Cl$',
         'CF': '$C-F$',
         'CH': '$C-H$',
         'CNHH': '$C-NH_2$',
         'CNOO': '$C-NO_2$',
         'CCOOH': '$C-COOH$',
         'CO': '$C=O$',
         'COH': '$C-OH$',
         'CSH': '$C-SH$',
         'N': '$N$',
         'O': '$O$',
         'S': '$S$',
         'CNHCHHH' : '$CNHCH_3$',
         'COCHHH'  : '$COCH_3$' }
class Funcs(object):
    def __init__(self):
        self.funcs = funcs_r
    def __getitem__(self, key):
        try:
            ret = self.funcs[key]
        except KeyError:
            ret = '${}$'.format(key)
        return ret
funcs = Funcs()

class Cycle(object):
    def __init__(self, iterable):
        self.iterable = iterable
    def __getitem__(self,i):
        #assert isinstance(i, int), 'argument has to be an integer {}'.format(i)
        try:
            return self.iterable[ i % len(self.iterable) ]
        except TypeError:
            return self.iterable[ i ]
    def __iter__(self):
        return iter(self.iterable)
    def __len__(self):
        return len(self.iterable)

def indtocon(index):
    #return [list(item) for item in index.split('_')]
    #return  [ findall('[A-Z][^A-Z]*',item) for item in index.split('_') ]
    return  tuple( findall('[A-Z0-9][^A-Z1-9]*',item) for item in index.split('_') )

if args.homo:
    from cclib.parser import ccopen
    import logging
    import fnmatch
    allfiles = os.listdir('databc')
    path = os.getcwd()

def get_homo(conf,printi=False):
    for file in allfiles:
        if fnmatch.fnmatch(file,  'diap_' + conf + '.log'):  
            filetje = file
            filetje = path + '/databc/' + filetje
            if printi: print filetje
    f = ccopen(filetje)
    f.logger.setLevel(logging.ERROR)
    datatje = f.parse()
    HOMO = datatje.myhomos[1]
    Ehomo=datatje.mymos[1]['alpha'][0][HOMO]
    #Ehomo= datatje.moenergies[0][datatje.homos[0]]
    #print 'conf:', conf, 'Ehomo:', Ehomo, 'Ehomo/27.211:', Ehomo/27.211
    Elumo= datatje.moenergies[0][datatje.homos[0]+1]
    if printi:
        print "myhomos:", datatje.myhomos
        print "moenergies:", datatje.mymos
        print "mymos[1]['alpha'][0][myhomos[1]]"
    return Ehomo

def make_table(confs,data):
    from collections import OrderedDict
    table = OrderedDict()
    for index, value in zip(confs,data):
        if not index in table:
            table[index] = value
    return table

def complexprint(data, func=lambda arg: arg, strfunc= lambda *s: s):
    ''' this function prints all first level items of a collection(list/tuple/dict) on one line 
    with the option of applying a function on each first level item.  
    a strfunc argument is available to be applied on each string encountered.
    '''
    def printje(item, level=0):
        if level>10:
            print "type was:", type(item)
            print "max recursion reached"
            raise SystemExit('stop')
        if type(item) in [list,tuple,dict]:
            for it in item:
                printje(it,level=level+1)
        else:
            if type(item)==str:
                for it in strfunc(item):
                    print it,
            else:
                print item,
        return

    for totalcycle in data:
        for siterun in totalcycle:
            item = func(siterun)
            printje(item)
            print
    else:
        print "&"*20
    return

def main():
    read_cyclesinfo(args.file)

def read_cyclesinfo(filename):
    ''' Reading cyclesinfo

    Input:
        - filename

    '''
    with open(filename,'r') as fid:
        data = [ item.split() for item in fid.read().splitlines() ]
    datar=[]
    confs=[]
    values=[]
    prop=1
    n=len(data)
    print 'len(data)', n
    homos = []
    for item in data:
        #print "item:",item
        conf = item[0].replace("'","")
        if not args.homo:
            indices = map(int,item[-3:])
            rest = map(float,item[1:-3])
            value = rest + indices
            item = [ item[0].replace("'","") ] + value
        else:
            sys.stdout.write('#')
            indices = map(int,item[-3:])
            rest = map(float,item[1:-3])
            homo = get_homo(conf)
            homos.append([conf,homo])
            IP = rest[0] * 27.2113838
            value = [ IP] + [-homo] + rest[1:] + indices
            item = [ item[0].replace("'","") ] + value
            if -homo> 5.0 and IP<6.6:
                print "probably an outlier:", conf, " ", item
                get_homo(conf,True)
                continue
        item[0]=item[0].split('_')
        if item[1]:
            datar.append(item)
            confs.append(conf)
            values.append(value)
    print "homos:", homos
    with open('homofile','w') as fid:
        for item in homos:
            line = '%s %s' % ( item[0], str(item[1]) )
            fid.write(str(item)+'\n')
    for br in datar:
        # each site wordt geformat tot 8 width. die worden samen gejoind en weer geformat samen met de rest
        print '{0} {1:8.5}  {2:3}  {3:3}  {4:3}'.format(' '.join(['{:8}'.format(item) for item in br[0]]),br[prop],br[-3],br[-2],br[-1])
    print "len(values):", len(values)
    maxmacrocycles= values[-1][-3]
    nsites = values[-1][-1]
    print "maxcycles:",maxmacrocycles #starts counting at 1
    print "nsites:", nsites+1 #starts counting at 0
    sites=[] #list of all the changing sites only
    for conf,value in zip(confs,values):
        siteindex=value[-2]
        site = conf.split('_')[siteindex]
        sites.append(site)

    # There are two main data containers:
    #    - totalruns    #on chronological order
    #    - totalsites   #in numbered site order
    ##################### make totalruns list ################
    cyclesdata=[]
    runs=[]
    macrocycle=0
    i=0
    maxnsites=0
    totalruns=[]
    total_conf_data = []
    #run over all macrocycles:
    #for j in range(1,maxmacrocycles+1):
    for j in range(maxmacrocycles+1):
        runsA=[]
        runsC=[] #for total configurations list
        #run over all sites in a cycles
        for k in range(nsites+1):
            runA=[]
            runC=[]
            # run over all substituents
            while True:
                #print "values[i]", values[i]
                #print "i=", i, "j=",j,"k=", k
                #as long as the site index and cycle index do not change:
                if values[i][-1]==k and values[i][-3]==j:
                    runA.append([sites[i],values[i]])
                    runC.append([confs[i],values[i]])

                    #print "Jos"
                    #print "runA:", runA
                else:
                    #print "geen Jos"
                    #i+=1
                    break
                i+=1
                if i>=len(values): break
                #print "runA:", runA
            #to get the list alphabetically ordered:
            sortA = sorted(runA)
            if len(runA)>maxnsites: maxnsites=len(runA) # to get the right ticks in the plots
            #then there is mostly one problem. The CO group is above the N group only for the
            #secondary positions. So we want to pick the CO group and place it at the end of the list
            #1. get a list of the substituents 
            subsA = [ item[0] for item in sortA]
            # check is 'CO' is in
            groups = ['CO','O','S']
            for group in groups:
                if group in subsA:
                    #get index of the group
                    igroup = subsA.index(group)
                    #take it from the list is pop
                    #and insert it at the last position of the list
                    sortA.insert(len(subsA)-1, sortA.pop(igroup))
            if not sortA==[]: runsA.append(sortA)
            if not runC==[]: runsC.append(runC)
        if not runsA==[]: totalruns.append(runsA)
        if not runsC==[]: total_conf_data.append(runsC)
    #print "runsA"
    #pp.pprint(runsA)

    print "TOTAL CONF DATA:"
    #print "total_conf_data[0]:", total_conf_data[0]
    print "args.datacolumn:", args.datacolumn
    complexprint(total_conf_data,                                                              ##############
                 func = lambda y: min(y, key= lambda x: x[1][args.datacolumn]),     #########    MIN MAX    !!!!!!!!!!!!!  MIN MAX CHANGE HERE!!!!
                 strfunc = lambda z: z.split('_') )                                           ##############


    # NOW FORMED ARE: TOTALRUNS
    #now restrict it to only the cycles we need.
    if args.minmax:
        m1 = int( args.minmax[0] )
        m2 = int( args.minmax[1] ) + 1
        totalruns = totalruns[:][m1:m2]

    #print "totalruns:"
    #pp.pprint(totalruns)
    print "best substituent per site per run:"
    complexprint(totalruns, func = lambda y: min(y, key= lambda x: x[1][args.datacolumn] ) )
    #for run in totalruns:
    #    for site in run:
    #        print min(site, key= lambda x: x[1][0])
    print '='*20


    #################  MAKE totalsites ####################
    # these were at chronological order. also make a totalruns with site order 0,1,2 etc.
    totalsites=deepcopy(totalruns)
    for runs in totalsites:
       runs.sort(key= lambda x: x[0][1][-2]) #runs sorts by number of site. the [0] is just arbitrary here because each elements has same values
    #print "totalsites:"
    #pp.pprint(totalsites)
    print '='*20

    ################## MAKE table with only single attendance:
    if args.table:
        table = make_table(confs,values)
        pp.pprint(table.items()[0:4])


    # plot of property vs dopant/substituent
    if args.pplot:
        from CINDES.utils.plotters import prop_substituent_last_cycle
        prop_substituent_last_cycle(totalsites, maxnsites, args.datacolumn)
        plt.show()

    if args.tplot: #get a tablebin like plot
        fontsize = 11

        # only for particular case: 
        def get_label():
            labels = ('1.1','1.2', '1.3', '1.4','2.1','2.2','2.3','3.1', '3.2', '3.3')
            #labels = map(str,range(1,4))
            labels = xrange(1,100)
            for label in labels:
                yield str(label)
        labels = get_label() # this is now an iterator !
        import seaborn as sb
        sb.set_style('whitegrid')
        colors = sb.hls_palette(10,l=.4) #l=lightness the smaller the darker. 
        print "tablebin-like plot"
        binlist = []
        start=0
        propertycount = args.datacolumn #which column to chose the data from. 0 = all 1.0
        for i in range(len(totalruns)):
             binlistje = []
             for j in range(len(totalruns[i])):
                 l = [ item[1][propertycount] for item in totalruns[i][j] ] 
                 #print "i,j:", i,j, "l:", l
                 a = list(enumerate(l,start))
                 start += len(l)
                 binlistje.append(a)
             binlist.append(binlistje)
        pp.pprint(binlist)
        #tags=['ro','bs','g^','c*','mp','yv','k+','r|','bd','gh']
        tags_r=['o','s','^','*','p','v','<','>','d','h']
        tags = Cycle(tags_r)
        for i in range(len(binlist)):
            l=0
            for j in range(len(binlist[i])):
                a = np.array(binlist[i][j]).T
                site = totalruns[i][j][0][1][-2]

                # cutoff 
                if False:
                    a[a>1000] = None
                    if np.isnan(a).any(): print "cutoff is applied and used!"

                print "len: tags:", len(tags), "len colors:", len(colors), "site:", site

                b, = plt.plot(a[0],a[1],tags[site]+'-',color=colors[site],
                                                       markersize=5)
                plt.setp(b, linewidth=1)
                l += len(a[0])
                ax=plt.gca()
                ax.xaxis.grid(False)
                if i==0:
                    b.set_label('site:'+str(site+1))
            x = binlist[i][-1][-1][0] + 0.5
            plt.axvline(x=x, linewidth=2, color = 'k')
            if True: #if want to plot labels see function above
                y = 5.05
                ax.text(x-0.5*l,y,next(labels), horizontalalignment='center',fontsize=fontsize)

        #to reorder the legend 
        ax = plt.gca()
        handles, labels = ax.get_legend_handles_labels()
        # sort both labels and handles by labels
        labels, handles = zip(*sorted(zip(labels, handles), key=lambda t: int(t[0][5:])))
        if True: #place legend outside plot
            box = ax.get_position()
            ax.set_position([box.x0, box.y0, box.width*0.8, box.height])
            ax.legend(handles,labels,loc='center left', bbox_to_anchor=(1,0.5), prop={'size':fontsize})
        else:
            ax.legend(handles, labels)
        leg = plt.gca().get_legend()
        ltext  = leg.get_texts()
        plt.setp(ltext, fontsize=14)
        #plt.ylabel('property value')
        plt.ylabel(args.label,fontsize = fontsize)
        #plt.tick_params(axis='x', labelsize=fontsize)
        plt.tick_params(axis='both', labelsize=fontsize)
        #plt.title('chronological order of property vs molecular structures')
        plt.show()

    #plot property values of first cycle versus property values of last cycle
    if False:
        xs = [ item[1][0] for listje in totalsites[0] for item in listje ] #values of first run
        ys = [ item[1][0] for listje in totalsites[-1] for item in listje ] #values of last run
        labels = [ item[0] for listje in totalsites[0] for item in listje ] 
        print "labels= " , labels
        plt.plot(xs,ys,'ro')
        for label, x, y in zip(labels,xs,ys):
            plt.annotate(
                label, xy = (x, y), xytext = (20, -20),
                textcoords = 'offset points', ha = 'left', va = 'bottom',
                bbox = dict(boxstyle = 'round,pad=0.5', fc = 'yellow', alpha = 0.5),
                arrowprops = dict(arrowstyle = '->', connectionstyle = 'arc3,rad=0'))
        xm = min([ min(xs),min(ys) ] )
        ym = max([ max(xs),max(ys) ] )
        print "xm:",xm, "ym:",ym
        xl = np.linspace(xm,ym,100)
        yl = xl
        plt.plot(xl,yl, 'k-')
        #plt.xlabel('stabvalues first cycle (kJ/mol)')
        #plt.ylabel('stabvalues last cycle (kJ/mol)')
        plt.xlabel(args.label + ' first cycle')
        plt.ylabel(args.label + ' last cycle')
        plt.title('last cycle vs. first cycle')
        plt.show()

    if args.cplot: #plot something to compare the different site
        from matplotlib.legend_handler import HandlerLine2D
        tags_r=['ro','bs','g^','c*','mp','yv','k+','r|','bd','gh']
        tags = Cycle(tags_r)
        X = []
        Y = []
        index = args.datacolumn
        print "len:" + "totalsites[0]:", len(totalsites[0]), "totalsites:", len(totalsites)
        print "tags[:len(totalsites[0])]", tags[:len(totalsites[0])]
        tags_new = [ tags[i] for i in range(len(totalsites[0])) ]
        for site0,site1,tag,i in zip(totalsites[0],totalsites[-1],tags_new,range(len(totalsites[0]))):
            print "totalsites[0]:", len(totalsites[0])
            print "totalsites[-1]:", len(totalsites[-1])
            xs = [ item[1][args.datacolumn] for item in site0 ]
            ys = [ item[1][args.datacolumn] for item in site1 ]
            labels = [ item[0] for item in site0 ]
            a, = plt.plot(xs,ys,tag)
            a.set_label('site:'+str(i+1))
            print "i:", i
            for label, x, y in zip(labels,xs,ys):
                if True: #for boxes set to True
                    plt.annotate(
                        label, xy = (x, y), xytext = (20, -20),
                        textcoords = 'offset points', ha = 'left', va = 'bottom',
                        bbox = dict(boxstyle = 'round,pad=0.5', fc = 'yellow', alpha = 0.5),
                        arrowprops = dict(arrowstyle = '->', connectionstyle = 'arc3,rad=0'))
            X.append(min([ min(xs),min(ys) ] ))
            Y.append(max([ max(xs),max(ys) ] ))
            #plt.legend(handler_map={a:HandlerLine2D(numpoints=4)})
        print "xm:",min(X), "ym:",max(Y)
        plt.legend(loc='best', shadow= True)
        #xl = np.linspace(min(X)*0.9,max(Y)*1.1,100)
        xl = np.linspace(min(X),max(Y),100)
        yl = xl
        plt.plot(xl[:],yl[:], 'k-')
        #plt.xlabel('stabvalues first cycle (kJ/mol)')
        #plt.xlabel('IP first cycle (a.u.)')
        #plt.xlabel('electron affinities first cycle (hartree)')
        #plt.xlabel('bandgap first cycle (eV)')

        #plt.ylabel('stabvalues last cycle (kJ/mol)')
        #plt.ylabel('IP last cycle (a.u.)')
        #plt.ylabel('bandgap last cycle (eV)')
        #plt.ylabel('electron affinities last cycle (hartree)')
        plt.xlabel(args.label + ' first cycle')
        plt.ylabel(args.label + ' last cycle')
        plt.title('last cycle vs. first cycle')
        plt.show()

    if args.splot:
        '''try subplot splot'''
        from matplotlib.legend_handler import HandlerLine2D
        tags_r=['ro','bs','g^','c*','mp','yv','k+','r|','bd','gh']
        tags = Cycle(tags_r)
        #subplots = tuple( (3,2,i) for i in range(1,7))
        X = []
        Y = []
        #f, axs = plt.subplots(3,2,sharex=True,sharey=True)
        nx,ny = set_nxy(len(totalsites[0]))
        print nx, ny
        f, axs = plt.subplots(ny,nx)
        axs2d = [ item for sublist in axs for item in sublist ]
        print "axs2d:",axs2d
        index = args.datacolumn
        tags_new = [ tags[i] for i in range(len(totalsites[0])) ]
        for site0,site1,tag,i in zip(totalsites[0],totalsites[-1],tags_new,range(len(totalsites[0]))):
            xs = [ item[1][index] for item in site0 ]
            ys = [ item[1][index] for item in site1 ]
            labels = [ item[index] for item in site0 ]
            #plt.subplot(*subplots[i])
            #a, = plt.plot(xs,ys,tag)
            a=axs2d[i]
            print a
            a.plot(xs,ys,tag,label='site:' + str(i+1))
            #f.set_label('site:'+str(i))
            for label, x, y in zip(labels,xs,ys):
                if True: #for boxes set to True
                    plt.annotate(
                        label, xy = (x, y), xytext = (20, -20),
                        textcoords = 'offset points', ha = 'left', va = 'bottom',
                        bbox = dict(boxstyle = 'round,pad=0.5', fc = 'yellow', alpha = 0.5),
                        arrowprops = dict(arrowstyle = '->', connectionstyle = 'arc3,rad=0'))
            X.append(min([ min(xs),min(ys) ] ))
            Y.append(max([ max(xs),max(ys) ] ))
            #plt.legend(handler_map={a:HandlerLine2D(numpoints=4)})
            print "xm:",min(X), "ym:",max(Y)
            #xl = np.linspace(min(X)*0.9,max(Y)*1.1,100)
            xl = np.linspace(min(X),max(Y),100)
            yl = xl
            a.plot(xl[:],yl[:], 'k-')
            #for the legend:
            handles, labels = a.get_legend_handles_labels()
            a.legend(handles, labels, loc='best', fancybox=True, framealpha=0.5, numpoints=1)
        # how many unneeded plots are there?
        unneed = nx*ny - len(totalsites[0])
        for i in range(1,unneed+1):
            print "i:", i
            axs2d[-i].set_frame_on(False)
            axs2d[-i].axes.get_yaxis().set_visible(False)
            axs2d[-i].axes.get_xaxis().set_visible(False)
            axs2d[-1].get_xaxis().tick_bottom()

        #plt.xlabel('stabvalues first cycle (kJ/mol)')
        #plt.xlabel('IP first cycle (a.u.)')
        #plt.xlabel('electron affinities first cycle (hartree)')
        suplabel('x',args.label + ' first cycle',labelpad=5)
        suplabel('y',args.label + ' last cycle',labelpad=4)
        #suplabel('x','bandgap first cycle (eV)',labelpad=5)
        #suplabel('y','bandgap last cycle (eV)',labelpad=4)
        #plt.xlabel('bandgap first cycle (eV)')
        #plt.ylabel('bandgap last cycle (eV)')
        #plt.ylabel('electron affinities last cycle (hartree)')
        f.suptitle('last cycle vs. first cycle')
        plt.show()
    #plt.axis([0,150,0,10])


    if args.regxy: # plots two properties vs each other. and fits a straight line through it
        import seaborn as sb
        from scipy import stats
        propx = [ item[0] for item in values ] 
        propy = [ item[1] for item in values ]
        propx,propy = zip(*list(set(zip(propx,propy))))
        plt.plot(propx,propy,'.r')
        slope, intersept, r_value, p_value, std_err = stats.linregress(propx,propy)
        print "slope:", slope
        print "intersept:", intersept
        print "p_value:", p_value
        print "std_err:", std_err
        print "R=",r_value**2
        x = sorted(propx)
        y = [ slope*xje+intersept for xje in x ]
        plt.plot(x, y, '-')
        plt.xlabel('IP (eV)')
        plt.ylabel('-E(HOMO) (eV)')
        #plt.xlabel('property1 IP(eV)')
        #plt.ylabel('property2 -Ehomoe(eV)')
        #plt.title('two properties regression')
        plt.show()

def set_nxy(n):
    xys = { '1':(1,1),
            '2':(2,1), '3':(2,2), '4':(2,2), '5':(3,2), '6':(3,2), '7':(4,2), '8':(4,2), '9':(3,3), '10':(4,3),
           '11':(4,3),'12':(4,3),'13':(5,3),'14':(5,3),'15':(5,3),'16':(4,4)
          }
    return xys[str(n)]


def suplabel(axis,label,label_prop=None,
             labelpad=5,
             ha='center',va='center'):
    ''' Add super ylabel or xlabel to the figure
    Similar to matplotlib.suptitle
    axis       - string: "x" or "y"
    label      - string
    label_prop - keyword dictionary for Text
    labelpad   - padding from the axis (default: 5)
    ha         - horizontal alignment (default: "center")
    va         - vertical alignment (default: "center")
    '''
    import matplotlib.pylab as pylab
    fig = pylab.gcf() #get currenct figure
    xmin = []
    ymin = []
    for ax in fig.axes:
        xmin.append(ax.get_position().xmin)
        ymin.append(ax.get_position().ymin)
    xmin,ymin = min(xmin),min(ymin)
    dpi = fig.dpi
    if axis.lower() == "y":
        rotation=90.
        x = xmin-float(labelpad)/dpi
        y = 0.5
    elif axis.lower() == 'x':
        rotation = 0.
        x = 0.5
        y = ymin - float(labelpad)/dpi
    else:
        raise Exception("Unexpected axis: x or y")
    if label_prop is None: 
        label_prop = dict()
    pylab.text(x,y,label,rotation=rotation,
               transform=fig.transFigure,
               ha=ha,va=va,
               **label_prop)






if __name__ == "__main__":
    main()
